EXEC AddParty @PartyId = 4, @Name = 'conservative', @Colour = '0000ff';
EXEC AddParty @PartyId = 15, @Name = 'labour', @Colour = 'ea1d0e';
EXEC AddParty @PartyId = 6, @Name = 'crossbench', @Colour = 'C0C0C0';
EXEC AddParty @PartyId = 17, @Name = 'liberal democrat', @Colour = 'f8a428';
EXEC AddParty @PartyId = 21, @Name = 'other', @Colour = 'C0C0C0';
EXEC AddParty @PartyId = 49, @Name = 'non-affiliated', @Colour = null;
EXEC AddParty @PartyId = 3, @Name = 'bishops', @Colour = '000000';
EXEC AddParty @PartyId = 29, @Name = 'scottish national party', @Colour = 'fcf28f';
EXEC AddParty @PartyId = 8, @Name = 'independent', @Colour = 'C0C0C0';
EXEC AddParty @PartyId = 32, @Name = 'social democratic party', @Colour = 'FFFF00';
EXEC AddParty @PartyId = 38, @Name = 'ulster unionist party', @Colour = '99CCFF';
EXEC AddParty @PartyId = 7, @Name = 'democratic Unionist Party', @Colour = '000080';
EXEC AddParty @PartyId = 30, @Name = 'sinn féin', @Colour = '99CC00';
EXEC AddParty @PartyId = 22, @Name = 'plaid cymru', @Colour = '3f8428';
EXEC AddParty @PartyId = 16, @Name = 'liberal', @Colour = 'C0C0C0';
EXEC AddParty @PartyId = 10, @Name = 'independent labour', @Colour = 'FF0000';
EXEC AddParty @PartyId = 31, @Name = 'social democratic & labour party', @Colour = 'CCFFCC';
EXEC AddParty @PartyId = 9, @Name = 'independent conservative', @Colour = '0000FF';