
services:
  sqlexpress:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "password"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"

  microservice:
    build:
      context: .
      dockerfile: src/members.Api/Dockerfile
    depends_on:
      - sqlexpress
    environment:
      ConnectionStrings__DefaultConnection: "Server=sqlexpress;Database=MembersDb;User Id=sa;Password=password;MultipleActiveResultSets=True;TrustServerCertificate=True"
    ports:
      - "80:80"

