
services:
  sqlexpress:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "password"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - ./init-scripts:/init-scripts

  microservice:
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - sqlexpress
    environment:
      ConnectionStrings__MembersConnectionString: "Server=sqlexpress;Database=MembersDb;User Id=sa;Password=password;MultipleActiveResultSets=True;TrustServerCertificate=True"
    ports:
      - "8080:80"

  init:
    image: mcr.microsoft.com/mssql-tools
    depends_on:
      - sqlexpress
    volumes:
      - ./init-scripts:/init-scripts
    entrypoint: /bin/sh -c "sleep 15 && /init-scripts/init-db.sh"

